app:
    resource: '@AppBundle/Controller/'
    type: annotation

api_platform:
  resource: .
  type: api_platform
  prefix: /api

champion_data:
  path: /champions
  controller: AppBundle\Controller\ChampionAction::championData

playerData:
  path: /summonerName
  controller: AppBundle\Controller\PlayerAction::playerData

