<?php

namespace AppBundle\Repository;

/**
 * ChampionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ChampionRepository extends \Doctrine\ORM\EntityRepository
{
}
