<?php

namespace AppBundle\Repository;

/**
 * MatchSummonerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MatchSummonerRepository extends \Doctrine\ORM\EntityRepository
{
}
