<?php

namespace AppBundle\Repository;

/**
 * SummonerInMatchRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SummonerInMatchRepository extends \Doctrine\ORM\EntityRepository
{
}
